[pytest]
filterwarnings =
    error
    ignore::pytest.PytestDeprecationWarning
    ignore:.*deprecated.*:DeprecationWarning:ezdxf
    ignore:.*deprecated.*:DeprecationWarning:pyparsing
    ignore::pyparsing.warnings.PyparsingDeprecationWarning
